DROP TABLE LOGINUSER IF EXISTS;
DROP TABLE TEST IF EXISTS;
DROP TABLE PERSON IF EXISTS;
DROP TABLE IMAGE IF EXISTS;

CREATE TABLE LOGINUSER(
	ID INT PRIMARY KEY,
	ACCOUNTID VARCHAR(60) NOT NULL,
	PASSWORD VARCHAR(60) NOT NULL);
	
INSERT INTO LOGINUSER VALUES(1,'admin','admin');   
   
CREATE TABLE TEST(ID INT PRIMARY KEY,
   NAME VARCHAR(255));
   
INSERT INTO TEST VALUES(1, 'personone');
INSERT INTO TEST VALUES(2, 'persontwo');


CREATE TABLE PERSON(ID INT PRIMARY KEY,
   NAME VARCHAR(255),
   EMAIL VARCHAR(255));
   
INSERT INTO PERSON VALUES(1, 'personone', 'personone@gamil.com');
INSERT INTO PERSON VALUES(2, 'persontwo', 'personotwo@gamil.com');
INSERT INTO PERSON VALUES(3, 'personthree', 'personothree@gamil.com');

CREATE TABLE IMAGE(
	ID INT PRIMARY KEY,
	NAME VARCHAR(255),
	IMAGE LONGBLOB NOT NULL);


